apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: llama-app 
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/graz-dev/llms-on-kubernetes.git' 
    targetRevision: HEAD
    path: tinyllama-gpu-chart 
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy: { automated: { prune: true, selfHeal: true } }