image:
  repository: ghcr.io/open-webui/open-webui
  tag: dev-slim
  pullPolicy: IfNotPresent

openaiApiBaseUrl: "http://llama-app-tinyllama-gpu-chart:8080/v1"

service:
  type: ClusterIP 
  port: 8080

persistence:
  enabled: true
  storageClass: standard 
  size: 1Gi