apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: ramalama-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ramalama-virtual-service
spec:
  hosts:
  - "*"
  gateways:
  - ramalama-gateway
  http:
  - match:
    - uri:
        prefix: /v1
    route:
    - destination:
        host: {{ include "ramalama-models.fullname" . }}-api-gateway.{{ .Release.Namespace }}.svc.cluster.local
        port:
          number: 8080
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: {{ include "ramalama-models.webui.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
        port:
          number: 8080
