apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: vllm-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: vllm-virtual-service
spec:
  hosts:
  - "*"
  gateways:
  - vllm-gateway
  http:
  - match:
    - uri:
        exact: /v1/models
    route:
    - destination:
        host: vllm-api-gateway
        port:
          number: 8080
  - match:
    - uri:
        prefix: /v1/
    route:
    - destination:
        host: vllm-api-gateway
        port:
          number: 8080
  - match:
    - uri:
        prefix: /health
    route:
    - destination:
        host: vllm-api-gateway
        port:
          number: 8080